select * from PRACOWNICY;

select P.NAZWISKO, P.ETAT, P.ID_ZESP, Z.NAZWA
from PRACOWNICY as P, ZESPOLY as Z
where P.ID_ZESP = Z.ID_ZESP
order by P.NAZWISKO;

SELECT NAZWISKO, CONCAT(SUBSTRING(ETAT, 1,2), ID_PRAC) AS KOD FROM PRACOWNICY;

SELECT NAZWISKO, REPLACE(REPLACE(REPLACE(NAZWISKO, "I", "X"), "M", "X"),"K", "X") FROM PRACOWNICY;

SELECT NAZWISKO, PLACA_POD * 1.15 AS PODWYZKA FROM PRACOWNICY;

SELECT NAZWISKO, PLACA_POD, PLACA_POD*0.2 AS INWESTYCJA, PLACA_POD*0.2*POW(1.1, 10) AS KAPITAL, (PLACA_POD*0.2*POW(1.1, 10) - PLACA_POD*0.2) AS ZYSK FROM PRACOWNICY;

SELECT NAZWISKO, ZATRUDNIONY, (2000 - YEAR(ZATRUDNIONY) ) AS STAZ_W_2000 FROM PRACOWNICY;

SELECT NAZWISKO, DATE_FORMAT(ZATRUDNIONY, "%M %d %Y") AS DATA_ZATRUDNIENIA FROM PRACOWNICY WHERE ID_ZESP=20;

SELECT DAYNAME(CURRENT_DATE) AS DZIS;

SELECT ID_ZESP, NAZWA, ADRES FROM ZESPOLY;

SELECT * FROM PRACOWNICY;

SELECT NAZWISKO, PLACA_POD * 12 FROM PRACOWNICY;

SELECT DISTINCT NAZWA AS ETAT FROM ETATY;

SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP FROM PRACOWNICY WHERE ETAT="ASYSTENT";

SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP IN(30,40);

SELECT NAZWISKO, ID_ZESP, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD BETWEEN 300 AND 800;

SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE NAZWISKO LIKE "%SKI";

SELECT ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD>1000 AND ID_SZEFA IS NOT NULL;

SELECT NAZWISKO, ID_ZESP FROM PRACOWNICY WHERE (NAZWISKO LIKE "M%" OR NAZWISKO LIKE "%SKI") AND ID_ZESP=20;

SELECT NAZWISKO, ETAT, PLACA_POD/160 AS STWKA FROM PRACOWNICY WHERE PLACA_POD NOT BETWEEN 400 AND 800 AND ETAT NOT IN ("ADIUNKT", "ASYSTENT", "STAZYSTA") ORDER BY STWKA;

SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD FROM PRACOWNICY WHERE (PLACA_POD+IFNULL(PLACA_DOD, 0))>1000 GROUP BY ETAT, NAZWISKO;

